<a href="https://colab.research.google.com/github/sergiocastro85/hyperblog/blob/master/bfs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

instalar libreria treelib

In [1]:
!pip install treelib

In [2]:
#importar 
from treelib import Tree

In [ ]:
#Instanciar un arbol
g=Tree()

In [ ]:
grafo={'U':{'V':2,'X':1,'W':5},
       'X':{'U':1,'V':2,'W':3,'Y':1},
       'V':{'U':2,'X':2,'W':3},
       'Y':{'X':1,'W':1,'Z':2},
       'W':{'V':3,'X':3,'Y':1,'Z':5},
       'Z':{'Y':2,'W':5}}

In [ ]:
pq=[]
visitados=[]
id=1

g=Tree()

nodo=g.create_node(tag='U',data=['U',0],identifier=id)

pq.append(nodo)

while len(pq) !=0:
  pq.sort(key=lambda X:X.data[1])
  nodo_actual=pq.pop(0)
  costo_actual=nodo_actual.data[1]
  if nodo_actual.tag=='Z':
    g.show()
  visitados.append(nodo_actual.tag)
  hijos=list(grafo[nodo_actual.tag].items())
  for hijo in hijos:
    id=id+1
    nodo_hijo=g.create_node(tag=hijo[0],data=list(hijo),identifier=id,parent=nodo_actual.identifier)
    costo_hijo=hijo[1]
    costo_acumulado=costo_actual+costo_hijo
    if hijo[0]not in visitados:
      lista=[nodo.tag for nodo in pq]
      if hijo[0] in lista:
        index=lista.index(hijo[0])
        if costo_acumulado < pq[index].data[1]:
          pq[index].data[1]=costo_hijo
      else:
        pq.append(nodo_hijo)


U
├── V
│   ├── U
│   ├── W
│   └── X
├── W
│   ├── V
│   ├── X
│   ├── Y
│   └── Z
└── X
    ├── U
    ├── V
    ├── W
    └── Y
        ├── W
        ├── X
        └── Z



In [ ]:
d=g.nodes
for clave in d:
  if g.is_ancestor (d[clave].identifier, nodo_actual.identifier):
    print (d[clave].data)
print (nodo_actual.data)


['U', 0]
['X', 1]
['Y', 1]
['Z', 2]


In [37]:
#DEFINIR FUNCION EXPANDIR NODO

def expandirnodo(estadoactual):
  L=[]
  if estadoactual=="A":
    L=["B","C"]
  elif estadoactual=="B":
    L=["Z"]
  elif estadoactual=="Z":
    L=["D","F"]
  elif estadoactual=="C":
    L=["F","G","H"]
  elif estadoactual=="F":
    L=["I"]
  elif estadoactual=="G":
    L=["J"]
  elif estadoactual=="H":
    L=["K"]
  elif estadoactual=="K":
    L=["L"]
  return L

In [45]:
from typing_extensions import ParamSpec
#Estado inial A, estado Objetivo L
Q=[]
T=Tree()
V=[]
Q.append("A")
V.append("B")
T.create_node(tag="A",identifier="A",data="A")
while len(Q)!=0:
  pos_actual=Q.pop(0)
  hijos=expandirnodo(pos_actual)
  for hijo in hijos:
    if hijo not in V:
      T.create_node(tag=hijo,identifier=hijo,parent=pos_actual,data=hijo)
      V.append(hijo)
      Q.append(hijo)
      if hijo=="L":
        T.show()
##print("no Hay Solución")
  

A
└── C
    ├── F
    │   └── I
    ├── G
    │   └── J
    └── H
        └── K
            └── L



In [3]:
import numpy as np

In [12]:
N=5

l=[]

datos=[1,2,3,4,5,6,0,0,0,7,8,9,10,11,12,13,0,0,14,0,0,0,0,0,0]

matriz=np.array(datos).reshape(N,N)


def expandirnodo(tablero, posactual):
  L=[]
  filactual=np.where(tablero==posactual)[0][0] #.where fila columna
  columnactual=np.where(tablero==posactual)[1][0]#
  
  if filactual!=tablero.shape[0]-1: ##tamaño restamos 1 

    pos=tablero[filactual+1][columnactual] ##derecha
    if pos!=0:
      L.append(pos)
  
  if filactual !=0:
    pos=tablero[filactual-1][columnactual] ##izquierda
    if pos!=0:
      L.append(pos)

  if columnactual!=tablero.shape[1]-1:
    pos=tablero[filactual][columnactual+1] #abajo
    if pos!=0:
      L.append(pos)
  
  if columnactual!=0:
    pos=tablero[filactual][columnactual-1]#arriba
    if pos!=0:
      L.append(pos)
  
  return L


resultado=expandirnodo(matriz,14)

#expandirnodo(matriz,14)
#print(matriz[0][0])
print(matriz)
print(resultado)

#print(np.where(matriz==11)[0][0])


#l.append(matriz[0:1])


#print(l)

[[ 1  2  3  4  5]
 [ 6  0  0  0  7]
 [ 8  9 10 11 12]
 [13  0  0 14  0]
 [ 0  0  0  0  0]]
[11]


In [14]:
Q=[]
T=Tree()
V=[]
Q.append(11)
V.append(11)
T.create_node(tag=11,identifier=11,data=11)
while len(Q)!=0:
  pos_actual=Q.pop(0)
  hijos=expandirnodo(matriz,pos_actual)
  for hijo in hijos:
    if hijo not in V:
      T.create_node(tag=hijo,identifier=hijo,parent=pos_actual,data=hijo)
      V.append(hijo)
      Q.append(hijo)
      if hijo==1:
        T.show()
##print("no Hay Solución")

11
├── 10
│   └── 9
│       └── 8
│           ├── 6
│           │   └── 1
│           └── 13
├── 12
│   └── 7
│       └── 5
│           └── 4
│               └── 3
└── 14



In [6]:
T.show()

11
├── 10
├── 12
└── 14



In [17]:
def bfs (tablero, posinicial, posfinal):
  Q=[]
  T=Tree()
  V=[]
  Q.append(posinicial)
  V.append(posinicial)
  T.create_node(tag=posinicial,identifier=posinicial,data=posinicial)
  while len(Q)!=0:
    pos_actual=Q.pop(0)
    hijos=expandirnodo(tablero,pos_actual)
    for hijo in hijos:
      if hijo not in V:
        T.create_node(tag=hijo,identifier=hijo,parent=pos_actual,data=hijo)
        V.append(hijo)
        Q.append(hijo)
        if hijo==posfinal:
          T.show()
  if hijo!=posfinal:
    print("no Hay Solución")
bfs(matriz,1,1)


no Hay Solución
